# Generated by Django 3.2.15 on 2023-01-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '8770_bulk_index_queue_insert'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='layersortorder',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='layersortorder',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='resourceinstance',
            name='descriptors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
